{
  "formatVersion": "1.1",
  "component": {
    "group": "com.course.project.varabei",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 9723,
          "sha512": "d008bc8b804b7bba3da1ea9b225aca47b895741b51ab74a12190cdbd30555b2d8db85dab0241aefb4b979b7c282cb569ac0a25550f707325b377eb8990f0f77d",
          "sha256": "06e171c7966652945f3ea05e51ee6ca29584cfbfe41145c3a866e181a795ee35",
          "sha1": "7769869ddda3c76dbb3b8e5468c8f6c1549118fd",
          "md5": "c493ab6d7ba3f66b99a33d54d2a74038"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 9723,
          "sha512": "d008bc8b804b7bba3da1ea9b225aca47b895741b51ab74a12190cdbd30555b2d8db85dab0241aefb4b979b7c282cb569ac0a25550f707325b377eb8990f0f77d",
          "sha256": "06e171c7966652945f3ea05e51ee6ca29584cfbfe41145c3a866e181a795ee35",
          "sha1": "7769869ddda3c76dbb3b8e5468c8f6c1549118fd",
          "md5": "c493ab6d7ba3f66b99a33d54d2a74038"
        }
      ]
    }
  ]
}
