{
  "formatVersion": "1.1",
  "component": {
    "group": "com.course.project.varabei",
    "module": "logging-starter",
    "version": "1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 9724,
          "sha512": "a04530baa459959f2b50ffc6941bcf67ffa79f136ed4467fe58ad6845b423925182d87d4377007feb478910004c3eac8640de36927726998dcbfee99eaa6350b",
          "sha256": "eeda16ebac49d531532abaa029e7c89615d6882926204b932145f487e88556b7",
          "sha1": "2adb9806de7e62fe8107adc2583c962cd5a069f8",
          "md5": "5411f96af75ad2f36d7e4de27fd1886e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 9724,
          "sha512": "a04530baa459959f2b50ffc6941bcf67ffa79f136ed4467fe58ad6845b423925182d87d4377007feb478910004c3eac8640de36927726998dcbfee99eaa6350b",
          "sha256": "eeda16ebac49d531532abaa029e7c89615d6882926204b932145f487e88556b7",
          "sha1": "2adb9806de7e62fe8107adc2583c962cd5a069f8",
          "md5": "5411f96af75ad2f36d7e4de27fd1886e"
        }
      ]
    }
  ]
}
